#!/bin/bash
#set -x

echo "Compiling C code"
gcc bin/SWscore.c -o bin/SWscore
gcc bin/vj.c -o bin/vj

echo "Changing permissions of executables"
chmod u+x swigh-score
chmod u+x swigh-compare
chmod u+x swigh-clonotype
chmod u+x bin/SWscoresequences.sh
chmod u+x bin/report.sh

echo "Finished configuration"
