#!/bin/bash
#set -x

echo "Compiling C code"
gcc bin/SWscore.c -o bin/SWscore

echo "Changing permissions of executables"
chmod u+x bin/SWscore
chmod u+x swigh-score
chmod u+x swigh-compare
chmod u+x bin/SWscoresequences.sh
chmod u+x bin/report.sh

echo "Finished configuration"
