#!/bin/bash
#set -x

echo "Compiling C code"
gcc bin/SWscore.c -o bin/SWscore
gcc bin/q-filter.c -o quality-filter -lm

echo "Changing permissions of executables"
chmod u+x swigh-score
chmod u+x swigh-clonotype-random
chmod u+x swigh-clonotype-sequence
chmod u+x swigh-clonotype-amplicon
chmod u+x bin/SWscoresequences.sh
chmod u+x bin/swigh-clonotype2flatfiles
chmod u+x swigh-report

echo "Finished configuration"
