#!/bin/bash

# USAGE: ./swigh-clonotype filename.out
# STOPPING PROCESS: pkill -9 swigh-clonotype


echo "Determining Variable and Joining gene from local Smith-Waterman alignment and swigh-score output (filename.out)"
echo "The analysis is based on the 10 most frequent sequences and 95% similarity threshold to previously provided clonal sequence"
echo "--------------------------------------------------------------------------"
echo ""
echo -e "J-gene similarity\tJ gene\tJ-gene sequence\tV-gene similarity\tV-gene sequence\tSequencing read"
cat $1 | awk '$2>0.95 {print}' |tr -d '@' | awk '{print $1}' |sort| uniq -c |tr ' ' '\t' | sort -k 1 -r | head | awk '{print $NF}' > swscore-clonotype.tmp && bin/vj swscore-clonotype.tmp bin/igmt-vgene.txt | tr ' ' '\t' > swscore-clonotype-v.tmp

bin/vj swscore-clonotype-v.tmp bin/igmt-jgene.txt

rm swscore-clonotype.tmp
rm swscore-clonotype-v.tmp


